// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeX5VJU9ORDsfIpfPxPiSM3LdS3vDjBhk',
    appId: '1:791934098017:android:9aa45c9b32ff50a69f2820',
    messagingSenderId: '791934098017',
    projectId: 'cepamm-55a99',
    storageBucket: 'cepamm-55a99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQvrpNgZkJl2k2yKCvBTd5y1Q24di8VzM',
    appId: '1:791934098017:ios:8e1f5f2d087048e49f2820',
    messagingSenderId: '791934098017',
    projectId: 'cepamm-55a99',
    storageBucket: 'cepamm-55a99.firebasestorage.app',
    iosBundleId: 'com.example.appCepamm',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8D9yL3ESTliJ9ZcJ9pJvqGTgLUXta-LU',
    appId: '1:791934098017:web:1e3405d53576fb8b9f2820',
    messagingSenderId: '791934098017',
    projectId: 'cepamm-55a99',
    authDomain: 'cepamm-55a99.firebaseapp.com',
    storageBucket: 'cepamm-55a99.firebasestorage.app',
    measurementId: 'G-G9R1374LL6',
  );
}
